# TARGET_BOARD_PLATFORM := tinsp
TARGET_CPU_ABI := armeabi

TARGET_NO_BOOTLOADER := true

BOARD_USES_GENERIC_AUDIO := true

BOARD_HAVE_BLUETOOTH := false
BOARD_HAVE_GPS := false

USE_CAMERA_STUB := true

BOARD_WPA_SUPPLICANT_DRIVER := WEXT
